import { collection, addDoc, getDocs, deleteDoc, doc, query } from "firebase/firestore";
import { db } from "./firebase";
import { Issue } from "../types";

export const clearSeedData = async () => {
  console.log("Clearing existing seed data from issues, verifications, status_updates, notifications...");
  const collectionsToClear = ["issues", "verifications", "status_updates", "notifications"];
  for (const colName of collectionsToClear) {
    try {
      const qSnapshot = await getDocs(collection(db, colName));
      for (const docSnapshot of qSnapshot.docs) {
        await deleteDoc(doc(db, colName, docSnapshot.id));
      }
      console.log(`Cleared collection: ${colName}`);
    } catch (e) {
      console.error(`Error clearing collection ${colName}:`, e);
    }
  }
};

const demoIssues: Omit<Issue, "id">[] = [
  {
    title: "Deep pothole forming near outer Ring Road block A, Connaught Place",
    description: "A large pothole has opened up on the main road, causing cars and bikes to swerve abruptly. It has been getting larger over the past week due to heavy vehicle flow. Pedestrians crossing here are at high risk of injury.",
    imageUrl: "https://images.unsplash.com/photo-1558618586-4ac46e84f7e4?w=800&q=80",
    category: "Pothole",
    severity: "High",
    confidence: 0.94,
    location: { lat: 28.6304, lng: 77.2177 },
    address: "Outer Circle Road, Connaught Place, New Delhi",
    locationType: "road",
    suggestedDepartment: "Road Maintenance",
    citizenSummary: "Dangerous deep pothole in Outer Circle Road causing vehicles to swerve.",
    authoritySummary: "Asphalt failure on busy road requiring urgent patching to prevent traffic hazard.",
    riskReason: "High risk of vehicle damage, sudden braking, or two-wheeler accidents.",
    spamRisk: "Low",
    verificationQuestion: "Is the pothole still unpatched and causing traffic swerving?",
    recommendedAction: "Send Road Maintenance patching unit for emergency cold-mix filling.",
    status: "Open",
    priorityScore: 65,
    priorityReasons: ["High severity rating", "Located on high-traffic main road", "Low spam risk"],
    verificationCount: 2,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Road Maintenance",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 1,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 1,
  },
  {
    title: "Water pipe burst and street flooding near Dwarka Sector 12 Metro",
    description: "An underground fresh water pipeline has burst, wasting thousands of liters of clean water and flooding the nearby street. The stagnant water has started to block the pedestrian lane and is creating breeding grounds for mosquitoes. Immediate action is needed from the water authority.",
    imageUrl: "https://images.unsplash.com/photo-1587040273238-9b4b4b4b6b4b?w=800&q=80",
    category: "Water Leakage",
    severity: "Medium",
    confidence: 0.91,
    location: { lat: 28.5925, lng: 77.0402 },
    address: "Near Metro Station Exit, Dwarka Sector 12, New Delhi",
    locationType: "bus stop",
    suggestedDepartment: "Water Board",
    citizenSummary: "Underground water pipe leakage flooding local street near metro station.",
    authoritySummary: "Pressurized freshwater main pipe rupture requiring excavation and line welding.",
    riskReason: "Massive resource waste and minor flooding blocking transit access.",
    spamRisk: "Low",
    verificationQuestion: "Is the freshwater still flowing actively across the roadway?",
    recommendedAction: "Isolate pipeline segment and dispatch pipe repair team.",
    status: "Open",
    priorityScore: 52,
    priorityReasons: ["Located at high-footfall metro exit", "Significant freshwater waste"],
    verificationCount: 3,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Water Board",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 3,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 3,
  },
  {
    title: "Multiple non-functional streetlights at Inner Circle Radial Road 2, Connaught Place",
    description: "At least three streetlights have been completely dark for over a week near the commercial blocks. This has created a very dark stretch in the evening, making it unsafe for shoppers and workers leaving late. Foot traffic has reduced due to safety concerns.",
    imageUrl: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=800&q=80",
    category: "Broken Streetlight",
    severity: "Medium",
    confidence: 0.89,
    location: { lat: 28.6315, lng: 77.2195 },
    address: "Radial Road 2, Connaught Place, New Delhi",
    locationType: "market",
    suggestedDepartment: "Electrical Maintenance",
    citizenSummary: "Dark commercial corridor due to non-functioning overhead streetlights.",
    authoritySummary: "Cable fault or bulb failure affecting public lighting infrastructure in Radial Road 2.",
    riskReason: "Pedestrian safety and retail area crime prevention hazard.",
    spamRisk: "Low",
    verificationQuestion: "Are the streetlights completely dark after 7 PM?",
    recommendedAction: "Inspect electrical junctions and replace faulty light fixtures.",
    status: "Verified",
    priorityScore: 58,
    priorityReasons: ["Located in high footfall commercial market", "Verified by local business owners"],
    verificationCount: 8,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Electrical Maintenance",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 5,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 4,
  },
  {
    title: "Overflowing community garbage bins near Lajpat Nagar Metro Station",
    description: "The public garbage collection point is overflowing with solid waste, spilling onto the adjacent footpath. Bins haven't been cleared for several days, attracting stray dogs and generating a massive odor. Pedestrians are forced to walk on the busy main road instead.",
    imageUrl: "https://images.unsplash.com/photo-1594979469-0f5d36e95527?w=800&q=80",
    category: "Garbage Overflow",
    severity: "High",
    confidence: 0.95,
    location: { lat: 28.5695, lng: 77.2450 },
    address: "Feroze Gandhi Road, Lajpat Nagar III, New Delhi",
    locationType: "bus stop",
    suggestedDepartment: "Sanitation Department",
    citizenSummary: "Overflowing garbage dump site blocking pedestrian sidewalks.",
    authoritySummary: "Solid waste accumulation due to missed collection schedules. Needs urgent dump truck.",
    riskReason: "Public health hazard, foul smells, and obstruction of transit path.",
    spamRisk: "Low",
    verificationQuestion: "Is the garbage still piled up outside the designated containers?",
    recommendedAction: "Send heavy compactor truck for deep site clearing.",
    status: "Resolved",
    priorityScore: 78,
    priorityReasons: ["High severity rating", "Located near public transit", "Verified by multiple citizens"],
    verificationCount: 14,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 5,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Sanitation Department",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 8,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 2,
  },
  {
    title: "Crumbling footpath tiles and broken concrete near Sector 12 Market complex",
    description: "The pedestrian sidewalk tiles have cracked and broken, leaving uneven holes. Multiple elderly residents have tripped and fallen here during evening walks. The walkway requires complete repaving to ensure accessibility.",
    imageUrl: "https://images.unsplash.com/photo-1558388084-d40a526c1f5f?w=800&q=80",
    category: "Damaged Infrastructure",
    severity: "Low",
    confidence: 0.88,
    location: { lat: 28.5912, lng: 77.0421 },
    address: "Pocket 4, Dwarka Sector 12, New Delhi",
    locationType: "residential",
    suggestedDepartment: "Public Works",
    citizenSummary: "Uneven and dangerous sidewalk tiles causing tripping hazards.",
    authoritySummary: "Sidewalk degradation due to structural wear. Footpath tile replacement required.",
    riskReason: "Tripping risk for senior citizens and disabled pedestrians.",
    spamRisk: "Low",
    verificationQuestion: "Are the tiles still loose and creating unstable walking ground?",
    recommendedAction: "Schedule masonry crew to replace broken pavers and level the concrete base.",
    status: "Confirmed",
    priorityScore: 42,
    priorityReasons: ["Tripping hazard", "Located in high-density residential zone"],
    verificationCount: 6,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 2,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Public Works",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 12,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 10,
  },
  {
    title: "Overflowing sewage and open manhole near Lajpat Nagar Central Market",
    description: "A deep manhole is completely open and overflowing with toxic sewage water right near the main entrance of the market. The foul smell has made it unbearable for shoppers, and the open pit poses a critical falling hazard for children and elderly. Urgent repairs and barricading are needed.",
    imageUrl: "https://images.unsplash.com/photo-1601979031-0b96ce904e4e?w=800&q=80",
    category: "Sewage Issue",
    severity: "Critical",
    confidence: 0.97,
    location: { lat: 28.5682, lng: 77.2431 },
    address: "Central Market Lane, Lajpat Nagar II, New Delhi",
    locationType: "market",
    suggestedDepartment: "Drainage Department",
    citizenSummary: "Open sewer bubbling over with toxic black wastewater in retail area.",
    authoritySummary: "Sewer block and missing manhole cover. High exposure to bio-hazard and falling danger.",
    riskReason: "Extreme biohazard risk and catastrophic physical injury from open pit.",
    spamRisk: "Low",
    verificationQuestion: "Is the manhole still uncovered and discharging sewage?",
    recommendedAction: "Erect immediate physical safety barriers and clear pipeline block.",
    status: "In Progress",
    priorityScore: 92,
    priorityReasons: ["Critical severity level", "Highly populated commercial market", "Direct public safety threat"],
    verificationCount: 15,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Drainage Department",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 15,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 13,
  },
  {
    title: "Heavy construction debris dumped on main road in Rohini Sector 15",
    description: "Someone has illegally dumped a massive pile of bricks, concrete blocks, and soil right on the left lane of Sector 15 main road. This has narrowed down the street significantly, creating major traffic bottlenecks during peak hours. No warning signs or reflective indicators are present.",
    imageUrl: "https://images.unsplash.com/photo-1545127398-14699872f8a8?w=800&q=80",
    category: "Road Blockage",
    severity: "High",
    confidence: 0.93,
    location: { lat: 28.7321, lng: 77.1215 },
    address: "Sector 15 Main Road, Rohini, New Delhi",
    locationType: "road",
    suggestedDepartment: "Traffic Management",
    citizenSummary: "Illegal dumping of construction materials blockading vehicle lane.",
    authoritySummary: "Unauthorized public road encroachment with commercial waste blocking lane.",
    riskReason: "High collision risk during night hours and severe morning gridlock.",
    spamRisk: "Low",
    verificationQuestion: "Is the pile of construction bricks still obstructing the left lane?",
    recommendedAction: "Order JCB loaders to clear the roadway and locate violator.",
    status: "Verified",
    priorityScore: 76,
    priorityReasons: ["High severity rating", "Blocks vehicle movement on main avenue"],
    verificationCount: 9,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Traffic Management",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 18,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 16,
  },
  {
    title: "Aggressive pack of stray dogs near public playground in Rohini Sector 8",
    description: "A pack of more than ten stray dogs has occupied the entrance of the Sector 8 neighborhood park. They are chasing children on bicycles and have bitten two residents over the past week. Parents are scared to let their kids play outside.",
    imageUrl: "https://images.unsplash.com/photo-1598300042882-a2c5d3c3c3c3?w=800&q=80",
    category: "Unsafe Public Area",
    severity: "High",
    confidence: 0.90,
    location: { lat: 28.7055, lng: 77.1189 },
    address: "Block B Park, Rohini Sector 8, New Delhi",
    locationType: "park",
    suggestedDepartment: "Community Volunteers",
    citizenSummary: "Vicious stray dog pack guarding community park entrance and biting children.",
    authoritySummary: "Stray dog proliferation near residential playground posing active safety risk.",
    riskReason: "Immediate danger of rabies transmission and severe injuries to children.",
    spamRisk: "Low",
    verificationQuestion: "Are the stray dogs still actively aggressive near the park gate?",
    recommendedAction: "Coordinate with animal welfare authorities for vaccination and shelter transport.",
    status: "Open",
    priorityScore: 68,
    priorityReasons: ["Vicious animals near children's playground", "Multiple resident complaints reported"],
    verificationCount: 4,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Community Volunteers",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 22,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 22,
  },
  {
    title: "Vandalism and defacing of public walls near Saket Community Center",
    description: "A large public boundary wall has been extensively defaced with offensive graffiti, ruining the aesthetic appeal of the neighborhood. Community members want to organize a clean-up drive but need official coordination and paint supplies.",
    imageUrl: "https://images.unsplash.com/photo-1561451213-7a-c3a4f7e0d9?w=800&q=80",
    category: "Other",
    severity: "Low",
    confidence: 0.86,
    location: { lat: 28.5244, lng: 77.2066 },
    address: "Community Center Lane, Saket, New Delhi",
    locationType: "high-footfall area",
    suggestedDepartment: "Community Volunteers",
    citizenSummary: "Graffiti and wall defacement on public assets.",
    authoritySummary: "Vandalism in a prominent area requiring paint restoration.",
    riskReason: "Erosion of civic pride and property value depreciation.",
    spamRisk: "Low",
    verificationQuestion: "Is the wall still painted with graffiti?",
    recommendedAction: "Provide paint kits to local neighborhood group to execute wall restoration.",
    status: "In Progress",
    priorityScore: 40,
    priorityReasons: ["Low severity rating", "Located in high-footfall area"],
    verificationCount: 5,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Community Volunteers",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 26,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 24,
  },
  {
    title: "Damaged and flickering traffic signal at Saket J-Block intersection",
    description: "The traffic signal at the J-block crossing is flickering erratically, sometimes turning off completely. This is causing extreme confusion and near-miss collisions at the intersection. Commuters are requesting urgent technical inspection.",
    imageUrl: "https://images.unsplash.com/photo-1558981852-426c173cd4b7?w=800&q=80",
    category: "Broken Streetlight",
    severity: "Medium",
    confidence: 0.92,
    location: { lat: 28.5218, lng: 77.2091 },
    address: "J-Block Intersection, Saket, New Delhi",
    locationType: "road",
    suggestedDepartment: "Electrical Maintenance",
    citizenSummary: "Traffic lights failing intermittently, creating gridlock and safety risks.",
    authoritySummary: "Relay board or power supply malfunction in traffic signal pole.",
    riskReason: "High probability of high-speed intersection vehicular collisions.",
    spamRisk: "Low",
    verificationQuestion: "Is the intersection traffic light still flickering during daytime?",
    recommendedAction: "Send electrical engineer to replace the control board and test loop.",
    status: "Resolved",
    priorityScore: 62,
    priorityReasons: ["Traffic safety risk at busy intersection", "Technical glitch verified"],
    verificationCount: 7,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 3,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Electrical Maintenance",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 30,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 28,
  },
  {
    title: "Cracked road surface and severe asphalt potholes at Vasant Kunj Sector C",
    description: "A long stretch of the main road has developed deep, interconnected cracks and crumbling asphalt. Cars are forced to crawl at extremely slow speeds, causing tailbacks that stretch for miles. The entire surface needs immediate scraping and resurfacing.",
    imageUrl: "https://images.unsplash.com/photo-1567604130959-78f3f1b6f8d8?w=800&q=80",
    category: "Pothole",
    severity: "High",
    confidence: 0.94,
    location: { lat: 28.5385, lng: 77.1422 },
    address: "Sector C Main Road, Vasant Kunj, New Delhi",
    locationType: "road",
    suggestedDepartment: "Road Maintenance",
    citizenSummary: "Disintegrated asphalt street forming a continuous chain of deep potholes.",
    authoritySummary: "Base course failure under heavy traffic loads. Complete scraping and overlay required.",
    riskReason: "Continuous vehicle suspension damage and regular morning gridlock.",
    spamRisk: "Low",
    verificationQuestion: "Is the road surface still completely disintegrated with potholes?",
    recommendedAction: "Initiate full resurfacing project on Sector C road.",
    status: "Confirmed",
    priorityScore: 82,
    priorityReasons: ["High severity rating", "Critical connection road in South Delhi"],
    verificationCount: 11,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 4,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Road Maintenance",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 34,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 30,
  },
  {
    title: "Illegal open-air dumping of commercial waste near Vasant Kunj Sector D DDA Flats",
    description: "Large amounts of restaurant wet waste and plastic packaging are being dumped behind the apartment complex. It has started to attract flies, rodents, and vultures, creating an unhygienic environment right next to a residential zone.",
    imageUrl: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&q=80",
    category: "Garbage Overflow",
    severity: "Medium",
    confidence: 0.89,
    location: { lat: 28.5342, lng: 77.1478 },
    address: "Behind DDA Flats, Sector D, Vasant Kunj, New Delhi",
    locationType: "residential",
    suggestedDepartment: "Sanitation Department",
    citizenSummary: "Commercial wet waste and garbage being dumped unlawfully in neighborhood.",
    authoritySummary: "Commercial food waste accumulation violating local hygiene laws.",
    riskReason: "Attraction of disease vectors like rats and crows near family homes.",
    spamRisk: "Low",
    verificationQuestion: "Is commercial waste still being dumped behind the apartments?",
    recommendedAction: "Clear waste dump and post warning signs against commercial littering.",
    status: "Open",
    priorityScore: 54,
    priorityReasons: ["Residential health threat", "Persistent neighborhood nuisance"],
    verificationCount: 5,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Sanitation Department",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 38,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 38,
  },
  {
    title: "Dangling high-voltage electrical wires near Karol Bagh Market shopping lane",
    description: "Exposed high-voltage wires have broken loose from an overhead transformer and are hanging low, just six feet above the crowded pedestrian lane. In the wet monsoon season, this is an incredibly dangerous shock hazard for thousands of daily shoppers.",
    imageUrl: "https://images.unsplash.com/photo-1541976590-713941681591?w=800&q=80",
    category: "Unsafe Public Area",
    severity: "Critical",
    confidence: 0.96,
    location: { lat: 28.6448, lng: 77.1915 },
    address: "Padam Singh Road, Karol Bagh, New Delhi",
    locationType: "market",
    suggestedDepartment: "Electrical Maintenance",
    citizenSummary: "Hanging electric lines dangling directly above public market shopping lanes.",
    authoritySummary: "Loose high-voltage overhead distribution cable snapped from terminal board.",
    riskReason: "High-level risk of fatal electrocution, especially during monsoon rains.",
    spamRisk: "Low",
    verificationQuestion: "Are the electrical cables still hanging down over the walking street?",
    recommendedAction: "Send emergency line crew to shut down transformer and secure cables.",
    status: "In Progress",
    priorityScore: 94,
    priorityReasons: ["Critical safety hazard", "Located in heavily crowded shopping district"],
    verificationCount: 13,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Electrical Maintenance",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 42,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 41,
  },
  {
    title: "Abandoned commercial delivery van blocking fire exit path in Karol Bagh",
    description: "A heavily rusted commercial vehicle has been left abandoned in a narrow service alleyway for over three weeks. The van is completely blocking the primary fire exit route for several high-rise retail stores, presenting a major safety risk.",
    imageUrl: "https://images.unsplash.com/photo-1599940824399-a2fa73c8d0be?w=800&q=80",
    category: "Road Blockage",
    severity: "High",
    confidence: 0.91,
    location: { lat: 28.6432, lng: 77.1899 },
    address: "Block 2 Service Alley, Karol Bagh, New Delhi",
    locationType: "high-footfall area",
    suggestedDepartment: "Traffic Management",
    citizenSummary: "Rusted junk vehicle blocking commercial emergency exits and fire lanes.",
    authoritySummary: "Unclaimed vehicle occupying fire-lane and service access. Immediate tow required.",
    riskReason: "Blocks rescue services in case of commercial building fire.",
    spamRisk: "Low",
    verificationQuestion: "Is the rusted delivery van still parked in the service lane?",
    recommendedAction: "Deploy heavy tow-truck to impound vehicle and free fire exit.",
    status: "Open",
    priorityScore: 70,
    priorityReasons: ["High severity rating", "Direct fire exit violation in dense area"],
    verificationCount: 4,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Traffic Management",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 45,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 45,
  },
  {
    title: "Vandalized park benches and broken playground swings in Noida Sector 18 Park",
    description: "Several heavy concrete benches in the community park have been shattered by vandals, and the children's slide has rusted and snapped. This has made the community's only green space unusable and dangerous for children.",
    imageUrl: "https://images.unsplash.com/photo-1558449907-e8b54d98db92?w=800&q=80",
    category: "Damaged Infrastructure",
    severity: "Medium",
    confidence: 0.88,
    location: { lat: 28.5708, lng: 77.3258 },
    address: "Sector 18 central park, Noida, Uttar Pradesh",
    locationType: "park",
    suggestedDepartment: "Public Works",
    citizenSummary: "Shattered concrete seating and damaged swing frames in children's park.",
    authoritySummary: "Public park amenity destruction. Masonry and welding crews required.",
    riskReason: "Injury hazard to children from sharp rusted swings and concrete fragments.",
    spamRisk: "Low",
    verificationQuestion: "Are the park benches still shattered and unusable?",
    recommendedAction: "Replace metal swing assembly and install three new stone benches.",
    status: "Verified",
    priorityScore: 61,
    priorityReasons: ["Medium severity rating", "Recreational area for children", "Verified by park users"],
    verificationCount: 7,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Public Works",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 48,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 46,
  },
  {
    title: "Severe waterlogging and drainage failure under Noida Sector 18 underpass",
    description: "The storm drainage system under the sector 18 underpass has completely collapsed, causing neck-deep water accumulation after brief showers. Multiple cars have stalled inside the tunnel, blocking all access between sectors.",
    imageUrl: "https://images.unsplash.com/photo-1584464491-9fe367ac5e54?w=800&q=80",
    category: "Sewage Issue",
    severity: "Critical",
    confidence: 0.95,
    location: { lat: 28.5691, lng: 77.3239 },
    address: "Underpass main crossing, Sector 18, Noida, Uttar Pradesh",
    locationType: "road",
    suggestedDepartment: "Drainage Department",
    citizenSummary: "Heavy flooding and drainage block under main commercial underpass.",
    authoritySummary: "Underpass drainage pump failure or severe silt blockage in the underground mains.",
    riskReason: "Underpass flooding drowning vehicles and paralyzing sector-to-sector connectivity.",
    spamRisk: "Low",
    verificationQuestion: "Is water still pooling deeply inside the Sector 18 underpass?",
    recommendedAction: "Send high-capacity diesel pump trucks to drain underpass and clear intake grates.",
    status: "Resolved",
    priorityScore: 89,
    priorityReasons: ["Critical severity rating", "Major traffic artery blocked", "High community verification"],
    verificationCount: 12,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 4,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Drainage Department",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 52,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 50,
  },
  {
    title: "Damaged doors and non-functioning water in Gurugram Cyber City public restroom",
    description: "The public convenience facility has broken doors, shattered washbasins, and no running water. This causes severe inconvenience to hundreds of delivery riders and security personnel working in the vicinity.",
    imageUrl: "https://images.unsplash.com/photo-1558618003-e0c4e5d7f8a8?w=800&q=80",
    category: "Unsafe Public Area",
    severity: "Medium",
    confidence: 0.89,
    location: { lat: 28.4952, lng: 77.0895 },
    address: "DLF Cyber City block C, Sector 24, Gurugram, Haryana",
    locationType: "high-footfall area",
    suggestedDepartment: "General Civic Helpdesk",
    citizenSummary: "Dilapidated public restroom without water or basic privacy in commercial hub.",
    authoritySummary: "Public utility plumbing failure and vandalism. Repair and water reconnection needed.",
    riskReason: "Extremely poor hygiene and lack of basic amenities in office zone.",
    spamRisk: "Low",
    verificationQuestion: "Is water supply still missing in the restrooms?",
    recommendedAction: "Send plumber to restore supply lines and replace sanitary fixtures.",
    status: "Verified",
    priorityScore: 59,
    priorityReasons: ["Medium severity rating", "Affects key gig-worker workforce", "Verified by local riders"],
    verificationCount: 10,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "General Civic Helpdesk",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 55,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 53,
  },
  {
    title: "Giant old Gulmohar tree fallen across busy main lane in Cyber City",
    description: "A large, old tree has collapsed across all three lanes of the main road, completely blocking access to several office towers. Traffic is backed up for several kilometers, and emergency services are unable to pass.",
    imageUrl: "https://images.unsplash.com/photo-1503503656929-f87c0f5d58d3?w=800&q=80",
    category: "Road Blockage",
    severity: "Critical",
    confidence: 0.98,
    location: { lat: 28.4975, lng: 77.0872 },
    address: "Phase II main boulevard, Cyber City, Gurugram, Haryana",
    locationType: "road",
    suggestedDepartment: "Traffic Management",
    citizenSummary: "Heavy tree trunk collapse blocking all traffic in Cyber City boulevard.",
    authoritySummary: "Fallen mature tree blocking primary roadway. Arborist and chainsaw units required.",
    riskReason: "Severe traffic disruption and absolute blockage of emergency response routes.",
    spamRisk: "Low",
    verificationQuestion: "Is the road still entirely blocked by the fallen tree?",
    recommendedAction: "Dispatch emergency road clearance vehicle with chainsaw operators to cut and remove debris.",
    status: "In Progress",
    priorityScore: 93,
    priorityReasons: ["Critical severity level", "Complete blockage of core business district avenue"],
    verificationCount: 15,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Traffic Management",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 57,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 56,
  },
  {
    title: "Flooded basement parking and leak in Greater Noida Residential Society Sector Delta",
    description: "A major water supply pipe in the underground level has cracked, flooding the basement parking area of Block B. Resident vehicles are partially submerged, and there are concerns of electrical short circuits in the building foundations.",
    imageUrl: "https://images.unsplash.com/photo-1570129477009-0e0e-7a4e2b3b?w=800&q=80",
    category: "Water Leakage",
    severity: "High",
    confidence: 0.93,
    location: { lat: 28.5082, lng: 77.5135 },
    address: "Block B, Delta I flats, Greater Noida, Uttar Pradesh",
    locationType: "residential",
    suggestedDepartment: "Water Board",
    citizenSummary: "Basement flood from massive cracked supply pipe near electrical boxes.",
    authoritySummary: "Ruptured high-pressure supply line in building basement causing localized pooling.",
    riskReason: "High threat of structural concrete damage and electrical fires.",
    spamRisk: "Low",
    verificationQuestion: "Is water continuing to rise in the residential basement?",
    recommendedAction: "Shut off society main valve and weld high-pressure main conduit.",
    status: "Resolved",
    priorityScore: 81,
    priorityReasons: ["High severity rating", "Threatens life and property of multi-story residency"],
    verificationCount: 11,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 4,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Water Board",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 59,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 57,
  },
  {
    title: "Footpath encroachment and pavement blockages in Sector Alpha 1",
    description: "The public footpath has been encroached upon by temporary shops and commercial debris, leaving no room for pedestrians. Senior citizens are forced to walk on the busy high-speed vehicular road. Local residents request clearing and restructuring.",
    imageUrl: "https://images.unsplash.com/photo-1515162304-6771e974-2d47?w=800&q=80",
    category: "Damaged Infrastructure",
    severity: "Medium",
    confidence: 0.87,
    location: { lat: 28.5115, lng: 77.5098 },
    address: "Alpha I commercial lane, Greater Noida, Uttar Pradesh",
    locationType: "residential",
    suggestedDepartment: "Public Works",
    citizenSummary: "Sidewalk blocked by vendors and construction piles, forcing residents to walk on the road.",
    authoritySummary: "Encroachment of pedestrian walkways. Clear-up drive and zoning checks needed.",
    riskReason: "High pedestrian safety hazard in commercial-residential transition zone.",
    spamRisk: "Low",
    verificationQuestion: "Is the footpath still blocked by stalls and trash piles?",
    recommendedAction: "Conduct municipal zoning inspection and clear illegal footpath build-ups.",
    status: "Confirmed",
    priorityScore: 60,
    priorityReasons: ["Pedestrian hazard", "Located in key public accessibility zone"],
    verificationCount: 8,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 3,
    duplicateOf: null,
    createdBy: "demo-user",
    assignedTo: "Public Works",
    createdAt: Date.now() - 24 * 60 * 60 * 1000 * 60,
    updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 58,
  }
];

export const loadDemoData = async () => {
  // Clear all existing seed data completely first
  await clearSeedData();

  console.log("Seeding 20 new high-quality realistic issues...");
  for (const issue of demoIssues) {
    const docRef = await addDoc(collection(db, "issues"), issue);
    
    // Create status updates
    let note = `System initialized issue with status ${issue.status}.`;
    if (issue.status === "Resolved" || issue.status === "Confirmed") {
      note = `Department resolved this issue: The repair crew completed all necessary physical repairs and restored the area to normal.`;
    } else if (issue.status === "In Progress") {
      note = `Department officer has been dispatched to the site to inspect and initiate repair work.`;
    } else if (issue.status === "Verified") {
      note = `Community residents have verified this report as an active, genuine civic concern.`;
    }
    
    await addDoc(collection(db, "status_updates"), {
        issueId: docRef.id,
        status: issue.status,
        note: note,
        updatedBy: "demo-admin",
        createdAt: issue.updatedAt || Date.now()
    });
  }
  console.log("Seeded 20 demo issues successfully.");
};

export const resetDemoData = async () => {
  // Reload demo data clears and seeds fresh
  await loadDemoData();
};

// Kept for backwards compatibility
export const seedDemoData = loadDemoData;
