import { collection, addDoc, getDocs, deleteDoc, doc, query, where } from "firebase/firestore";
import { db } from "./firebase";
import { Issue } from "../types";

const demoIssues: Omit<Issue, "id">[] = [
    {
      title: "Deep Pothole near School Entrance",
      description:
        "Massive pothole right before the crosswalk. Cars are swerving dangerously.",
      imageUrl:
        "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=400",
      category: "Pothole",
      severity: "Critical",
      confidence: 0.95,
      location: { lat: 28.6139, lng: 77.209 },
      address: "School Road",
      locationType: "school",
      suggestedDepartment: "Road Maintenance",
      citizenSummary: "Dangerous pothole near school causing swerving.",
      authoritySummary:
        "Immediate pothole repair required near school crosswalk to prevent accidents.",
      riskReason: "High risk of traffic accident or pedestrian injury.",
      spamRisk: "Low",
      verificationQuestion: "Is the pothole still open and unguarded?",
      recommendedAction: "Dispatch emergency repair crew.",
      status: "In Progress",
      priorityScore: 87,
      priorityReasons: [
        "Critical severity",
        "Located near a school",
        "High verification count",
      ],
      verificationCount: 18,
      disputeCount: 0,
      duplicateCount: 0,
      confirmedResolvedCount: 0,
      duplicateOf: null,
      createdBy: "demo-user",
      assignedTo: "Team Alpha",
      createdAt: Date.now() - 24 * 60 * 60 * 1000 * 2,
      updatedAt: Date.now() - 24 * 60 * 60 * 1000,
    },
    {
      title: "Garbage Overflowing on Sidewalk",
      description:
        "Bins haven't been cleared for 3 days. Trash is spilling onto the street.",
      imageUrl:
        "https://images.unsplash.com/photo-1605600659928-8fa82b21235b?auto=format&fit=crop&q=80&w=400",
      category: "Garbage Overflow",
      severity: "High",
      confidence: 0.92,
      location: { lat: 28.6145, lng: 77.208 },
      address: "Market Chowk",
      locationType: "market",
      suggestedDepartment: "Sanitation Department",
      citizenSummary: "Trash bins overflowing onto the sidewalk.",
      authoritySummary:
        "Delayed garbage collection leading to sidewalk blockage and health hazard.",
      riskReason: "Health hazard and public nuisance in commercial area.",
      spamRisk: "Low",
      verificationQuestion: "Has the garbage truck arrived today?",
      recommendedAction: "Schedule immediate pickup.",
      status: "Verified",
      priorityScore: 72,
      priorityReasons: [
        "High severity",
        "Pending for more than 3 days",
        "Located in market",
      ],
      verificationCount: 12,
      disputeCount: 0,
      duplicateCount: 0,
      confirmedResolvedCount: 0,
      duplicateOf: null,
      createdBy: "demo-user",
      assignedTo: null,
      createdAt: Date.now() - 24 * 60 * 60 * 1000 * 4,
      updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 3,
    },
    {
      title: "Water Pipe Leaking",
      description:
        "Continuous water flow from broken pipe next to the bus stand.",
      imageUrl:
        "https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&q=80&w=400",
      category: "Water Leakage",
      severity: "Medium",
      confidence: 0.88,
      location: { lat: 28.615, lng: 77.207 },
      address: "Bus Stand Lane",
      locationType: "bus stop",
      suggestedDepartment: "Water Board",
      citizenSummary: "Wastage of clean water due to broken pipe.",
      authoritySummary: "Municipal water supply pipe rupture needing welding.",
      riskReason: "Resource wastage and potential minor flooding.",
      spamRisk: "Low",
      verificationQuestion: "Is the water still leaking actively?",
      recommendedAction: "Send plumber to inspect and seal leak.",
      status: "Open",
      priorityScore: 50,
      priorityReasons: ["Located at bus stop", "Water resource wastage"],
      verificationCount: 3,
      disputeCount: 0,
      duplicateCount: 0,
      confirmedResolvedCount: 0,
      duplicateOf: null,
      createdBy: "demo-user",
      assignedTo: null,
      createdAt: Date.now() - 24 * 60 * 60 * 1000 * 1,
      updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 1,
    },
    {
      title: "Shattered Streetlight Glass",
      description:
        "Streetlight glass is broken and dangling dangerously over the path.",
      imageUrl:
        "https://images.unsplash.com/photo-1524660988542-c440de9ce0f1?auto=format&fit=crop&q=80&w=400",
      category: "Broken Streetlight",
      severity: "High",
      confidence: 0.9,
      location: { lat: 28.616, lng: 77.206 },
      address: "Green Park Colony",
      locationType: "residential",
      suggestedDepartment: "Electrical Maintenance",
      citizenSummary: "Broken streetlight glass hanging above sidewalk.",
      authoritySummary:
        "Physical damage to streetlight housing; risk of falling glass.",
      riskReason: "Physical danger to pedestrians below.",
      spamRisk: "Low",
      verificationQuestion: "Is the glass still hanging from the pole?",
      recommendedAction: "Dispatch bucket truck to secure housing.",
      status: "Resolved",
      priorityScore: 65,
      priorityReasons: ["High severity", "Physical danger"],
      verificationCount: 7,
      disputeCount: 0,
      duplicateCount: 0,
      confirmedResolvedCount: 2,
      duplicateOf: null,
      createdBy: "demo-user",
      assignedTo: "Team Beta",
      createdAt: Date.now() - 24 * 60 * 60 * 1000 * 5,
      updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 1,
    },
    {
      title: "Open Sewage Cover",
      description:
        "Manhole cover is completely missing in the middle of the road.",
      imageUrl:
        "https://images.unsplash.com/photo-1626248359281-99571ff76472?auto=format&fit=crop&q=80&w=400",
      category: "Sewage Issue",
      severity: "Critical",
      confidence: 0.98,
      location: { lat: 28.617, lng: 77.205 },
      address: "Hospital Road",
      locationType: "hospital",
      suggestedDepartment: "Drainage Department",
      citizenSummary: "Missing manhole cover creates a massive hazard.",
      authoritySummary:
        "Stolen or broken manhole cover exposing deep sewage drop.",
      riskReason: "Extreme risk of vehicles or pedestrians falling in.",
      spamRisk: "Low",
      verificationQuestion: "Is the hole still uncovered?",
      recommendedAction: "Immediately barricade and replace cover.",
      status: "Verified",
      priorityScore: 95,
      priorityReasons: [
        "Critical severity",
        "Located near hospital",
        "Direct safety risk",
      ],
      verificationCount: 25,
      disputeCount: 0,
      duplicateCount: 0,
      confirmedResolvedCount: 0,
      duplicateOf: null,
      createdBy: "demo-user",
      assignedTo: null,
      createdAt: Date.now() - 24 * 60 * 60 * 1000 * 0.5,
      updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 0.2,
    },
    {
      title: "Broken Bus Stop Bench",
      description: "The seating at the bus stop is completely collapsed.",
      imageUrl:
        "https://images.unsplash.com/photo-1610486001222-63231e33abf4?auto=format&fit=crop&q=80&w=400",
      category: "Damaged Infrastructure",
      severity: "Low",
      confidence: 0.85,
      location: { lat: 28.618, lng: 77.204 },
      address: "Sector 8 Main Road",
      locationType: "bus stop",
      suggestedDepartment: "Public Works",
      citizenSummary: "Bus stop seating is broken and unusable.",
      authoritySummary:
        "Vandalized or deteriorated public seating requires replacement.",
      riskReason: "Inconvenience to elderly and disabled transit users.",
      spamRisk: "Low",
      verificationQuestion: "Is the bench still broken?",
      recommendedAction: "Schedule repair for transit stop.",
      status: "Open",
      priorityScore: 30,
      priorityReasons: ["Low severity", "Transit stop amenity"],
      verificationCount: 0,
      disputeCount: 0,
      duplicateCount: 0,
      confirmedResolvedCount: 0,
      duplicateOf: null,
      createdBy: "demo-user",
      assignedTo: null,
      createdAt: Date.now() - 10000,
      updatedAt: Date.now() - 10000,
    },
    {
      title: "Minor Pothole",
      description: "Small pothole forming on the side of the road.",
      imageUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=400",
      category: "Pothole",
      severity: "Low",
      confidence: 0.8,
      location: { lat: 28.62, lng: 77.21 },
      address: "Lake View Street",
      locationType: "road",
      suggestedDepartment: "Road Maintenance",
      citizenSummary: "Small pothole starting to form.",
      authoritySummary: "Minor surface degradation.",
      riskReason: "Minor vehicle wear.",
      spamRisk: "Low",
      verificationQuestion: "Has the pothole gotten bigger?",
      recommendedAction: "Add to routine patching schedule.",
      status: "Open",
      priorityScore: 15,
      priorityReasons: ["Low severity"],
      verificationCount: 0,
      disputeCount: 0,
      duplicateCount: 0,
      confirmedResolvedCount: 0,
      duplicateOf: null,
      createdBy: "demo-user",
      assignedTo: null,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    {
      title: "Garbage Bags Dumped",
      description: "Several black trash bags dumped illegally.",
      imageUrl: "https://images.unsplash.com/photo-1605600659928-8fa82b21235b?auto=format&fit=crop&q=80&w=400",
      category: "Garbage Overflow",
      severity: "Medium",
      confidence: 0.9,
      location: { lat: 28.622, lng: 77.215 },
      address: "Metro Station Exit",
      locationType: "high-footfall area",
      suggestedDepartment: "Sanitation Department",
      citizenSummary: "Illegal dumping near metro.",
      authoritySummary: "Illegal dumping requires removal.",
      riskReason: "Odor and hygiene issue.",
      spamRisk: "Low",
      verificationQuestion: "Are the bags still there?",
      recommendedAction: "Dispatch cleanup crew.",
      status: "Confirmed",
      priorityScore: 40,
      priorityReasons: ["Medium severity", "High-footfall area"],
      verificationCount: 5,
      disputeCount: 0,
      duplicateCount: 0,
      confirmedResolvedCount: 3,
      duplicateOf: null,
      createdBy: "demo-user",
      assignedTo: "Team Clean",
      createdAt: Date.now() - 24 * 60 * 60 * 1000 * 10,
      updatedAt: Date.now() - 24 * 60 * 60 * 1000 * 5,
    },
    {
      title: "Flickering Streetlight",
      description: "Streetlight flashes on and off constantly.",
      imageUrl: "https://images.unsplash.com/photo-1524660988542-c440de9ce0f1?auto=format&fit=crop&q=80&w=400",
      category: "Broken Streetlight",
      severity: "Low",
      confidence: 0.85,
      location: { lat: 28.625, lng: 77.22 },
      address: "Residential Lane 4",
      locationType: "residential",
      suggestedDepartment: "Electrical Maintenance",
      citizenSummary: "Flickering light is annoying.",
      authoritySummary: "Bulb or ballast failing.",
      riskReason: "Reduced visibility at night.",
      spamRisk: "Low",
      verificationQuestion: "Is it still flickering tonight?",
      recommendedAction: "Replace bulb/ballast.",
      status: "Open",
      priorityScore: 10,
      priorityReasons: ["Low severity"],
      verificationCount: 1,
      disputeCount: 0,
      duplicateCount: 0,
      confirmedResolvedCount: 0,
      duplicateOf: null,
      createdBy: "demo-user",
      assignedTo: null,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    {
      title: "Pothole Clusters",
      description: "Multiple potholes in a 50m stretch.",
      imageUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=400",
      category: "Pothole",
      severity: "High",
      confidence: 0.9,
      location: { lat: 28.63, lng: 77.225 },
      address: "Industrial bypass",
      locationType: "road",
      suggestedDepartment: "Road Maintenance",
      citizenSummary: "Very rough road with many potholes.",
      authoritySummary: "Extensive surface damage.",
      riskReason: "Vehicle damage and swerving hazard.",
      spamRisk: "Low",
      verificationQuestion: "Is the road still unpatched?",
      recommendedAction: "Repave section.",
      status: "Verified",
      priorityScore: 65,
      priorityReasons: ["High severity", "Multiple verifications"],
      verificationCount: 15,
      disputeCount: 0,
      duplicateCount: 0,
      confirmedResolvedCount: 0,
      duplicateOf: null,
      createdBy: "demo-user",
      assignedTo: null,
      createdAt: Date.now() - 24 * 60 * 60 * 1000,
      updatedAt: Date.now(),
    },
    {
      title: "Commercial Waste Bin Overflow",
      description: "Restaurant waste spilling out.",
      imageUrl: "https://images.unsplash.com/photo-1605600659928-8fa82b21235b?auto=format&fit=crop&q=80&w=400",
      category: "Garbage Overflow",
      severity: "Medium",
      confidence: 0.9,
      location: { lat: 28.635, lng: 77.23 },
      address: "Food Street",
      locationType: "market",
      suggestedDepartment: "Sanitation Department",
      citizenSummary: "Commercial bins overflowing.",
      authoritySummary: "Commercial waste pickup missed.",
      riskReason: "Rodent attraction.",
      spamRisk: "Low",
      verificationQuestion: "Is the bin still full?",
      recommendedAction: "Fine business or force pickup.",
      status: "Open",
      priorityScore: 35,
      priorityReasons: ["Medium severity", "Market area"],
      verificationCount: 2,
      disputeCount: 0,
      duplicateCount: 0,
      confirmedResolvedCount: 0,
      duplicateOf: null,
      createdBy: "demo-user",
      assignedTo: null,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    {
      title: "Dripping Pipeline Valve",
      description: "Valve is dripping water slowly.",
      imageUrl: "https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&q=80&w=400",
      category: "Water Leakage",
      severity: "Low",
      confidence: 0.8,
      location: { lat: 28.64, lng: 77.235 },
      address: "Park Corner",
      locationType: "park",
      suggestedDepartment: "Water Board",
      citizenSummary: "Slow leak from pipe.",
      authoritySummary: "Valve requires tightening.",
      riskReason: "Minor water waste.",
      spamRisk: "Low",
      verificationQuestion: "Is it still dripping?",
      recommendedAction: "Routine maintenance.",
      status: "In Progress",
      priorityScore: 15,
      priorityReasons: ["Low severity"],
      verificationCount: 1,
      disputeCount: 0,
      duplicateCount: 0,
      confirmedResolvedCount: 0,
      duplicateOf: null,
      createdBy: "demo-user",
      assignedTo: "Team Delta",
      createdAt: Date.now() - 24 * 60 * 60 * 1000 * 2,
      updatedAt: Date.now(),
    },
];

export const loadDemoData = async () => {
  const querySnapshot = await getDocs(query(collection(db, "issues"), where("createdBy", "==", "demo-user")));
  if (!querySnapshot.empty) {
    console.log("Demo data already loaded");
    return;
  }

  for (const issue of demoIssues) {
    const docRef = await addDoc(collection(db, "issues"), issue);
    
    // Create initial status update
    await addDoc(collection(db, "status_updates"), {
        issueId: docRef.id,
        status: issue.status,
        note: `System initialized issue with status ${issue.status}.`,
        updatedBy: "demo-admin",
        createdAt: issue.updatedAt || Date.now()
    });
  }
  console.log("Seeded 12 demo issues successfully.");
};

export const resetDemoData = async () => {
  // Delete existing demo issues
  const qIssues = query(collection(db, "issues"), where("createdBy", "==", "demo-user"));
  const issueSnapshots = await getDocs(qIssues);
  
  for (const docSnapshot of issueSnapshots.docs) {
      await deleteDoc(doc(db, "issues", docSnapshot.id));
      
      // Delete related status updates
      const qStatus = query(collection(db, "status_updates"), where("issueId", "==", docSnapshot.id));
      const statusSnapshots = await getDocs(qStatus);
      for (const statusDoc of statusSnapshots.docs) {
          await deleteDoc(doc(db, "status_updates", statusDoc.id));
      }
      
      // Delete related verifications
      const qVerifications = query(collection(db, "verifications"), where("issueId", "==", docSnapshot.id));
      const verificationSnapshots = await getDocs(qVerifications);
      for (const verifDoc of verificationSnapshots.docs) {
          await deleteDoc(doc(db, "verifications", verifDoc.id));
      }
  }

  // Reload demo data
  await loadDemoData();
};

// Kept for backwards compatibility
export const seedDemoData = loadDemoData;
