import React, { useState } from "react";
import { NeumorphicCard } from "../card";
import { BrainCircuit, Info, ChevronDown, ChevronUp } from "lucide-react";
import { Issue, Verification, AIExplanation } from "../../../types";
import { CivicIntelligence } from "../../../lib/ai/intelligence";
import { motion, AnimatePresence } from "motion/react";

export function AIExplainabilityWidget({
  issue,
  verifications,
}: {
  issue: Issue;
  verifications: Verification[];
}) {
  const [explanation, setExplanation] = useState<AIExplanation | null>(null);
  const [loading, setLoading] = useState(false);
  const [isOpen, setIsOpen] = useState(false);

  const handleExplain = async () => {
    if (!isOpen) {
      setIsOpen(true);
      if (!explanation) {
        setLoading(true);
        const result = await CivicIntelligence.explainIssue(
          issue,
          verifications,
        );
        setExplanation(result);
        setLoading(false);
      }
    } else {
      setIsOpen(false);
    }
  };

  return (
    <NeumorphicCard className="mt-4 p-0 overflow-hidden bg-[var(--color-civic-surface-inset)] shadow-[var(--shadow-neumorphic-inset)] border border-transparent">
      <button
        onClick={handleExplain}
        className="w-full p-3 flex items-center justify-between hover:bg-[var(--color-civic-surface)] transition-colors"
      >
        <div className="flex items-center gap-2">
          <BrainCircuit className="w-4 h-4 text-[var(--color-civic-primary)]" />
          <span className="text-xs font-bold text-[var(--color-civic-text-secondary)] uppercase tracking-wider">
            AI Priority Explanation
          </span>
        </div>
        {isOpen ? (
          <ChevronUp className="w-4 h-4 text-[var(--color-civic-text-muted)]" />
        ) : (
          <ChevronDown className="w-4 h-4 text-[var(--color-civic-text-muted)]" />
        )}
      </button>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden"
          >
            <div className="p-4 pt-0 border-t border-[var(--color-civic-border)]">
              {loading ? (
                <div className="flex items-center gap-2 text-sm text-[var(--color-civic-text-muted)] animate-pulse py-2">
                  <div className="w-4 h-4 rounded-full border-2 border-[var(--color-civic-primary)] border-t-transparent animate-spin" />
                  Generating context...
                </div>
              ) : explanation ? (
                <div className="space-y-3 mt-3">
                  <p className="text-sm text-[var(--color-civic-text-primary)] font-medium leading-relaxed">
                    {explanation.explanation}
                  </p>

                  {explanation.factors && explanation.factors.length > 0 && (
                    <div className="space-y-1.5">
                      <span className="text-[10px] font-bold text-[var(--color-civic-text-muted)] uppercase tracking-widest block mb-2">
                        Key Factors
                      </span>
                      {explanation.factors.map((factor, idx) => (
                        <div
                          key={idx}
                          className="flex items-start gap-2 text-xs"
                        >
                          <Info className="w-3.5 h-3.5 text-[var(--color-civic-priority-medium)] mt-0.5 shrink-0" />
                          <span className="text-[var(--color-civic-text-secondary)]">
                            {factor}
                          </span>
                        </div>
                      ))}
                    </div>
                  )}

                  <div className="flex justify-between items-center pt-2 mt-2 border-t border-[var(--color-civic-border)]">
                    <span className="text-[10px] text-[var(--color-civic-text-muted)]">
                      Generated by CivicVision AI
                    </span>
                    <span className="text-[10px] font-bold px-2 py-1 bg-[var(--color-civic-surface)] rounded-full shadow-[var(--shadow-neumorphic)] text-[var(--color-civic-primary)]">
                      Confidence:{" "}
                      {Math.round((explanation.confidence || 0.9) * 100)}%
                    </span>
                  </div>
                </div>
              ) : (
                <div className="text-sm text-[var(--color-civic-text-muted)] py-2">
                  Failed to generate explanation.
                </div>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </NeumorphicCard>
  );
}
