import "dotenv/config";
process.env.GCLOUD_PROJECT = "zenith-a6ada";
process.env.GOOGLE_CLOUD_PROJECT = "zenith-a6ada";
import { initializeApp, applicationDefault, cert } from "firebase-admin/app";
import { getFirestore as getAdminFirestore, Timestamp } from "firebase-admin/firestore";
const getFirestore = () => getAdminFirestore("ai-studio-zenith-a4e5dd9f-7c11-46ac-a8ac-4777cb65f044");

try {
  let credential = undefined;
  if (process.env.FIREBASE_SERVICE_ACCOUNT_KEY) {
    credential = cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_KEY));
  } else {
    credential = applicationDefault();
  }
  initializeApp({
    credential,
    projectId: "zenith-a6ada",
  });
} catch (e) {
  console.log("Firebase Admin already initialized or failed to initialize via ADC:", e);
}

const db = getFirestore();

// Helper to add days
const addDays = (date: Date, days: number) => {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
};

const issues = [
  // 3 Potholes
  {
    title: "Large Pothole on School Road",
    description: "Deep pothole causing traffic jams near the school entrance.",
    imageUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80",
    category: "Pothole",
    severity: "High",
    confidence: 0.85,
    location: { lat: 28.6139, lng: 77.2090 },
    address: "School Road, Block C",
    locationType: "school",
    suggestedDepartment: "Road Maintenance",
    citizenSummary: "A large pothole on School Road is slowing down traffic and posing a risk to two-wheelers.",
    authoritySummary: "High severity road damage requiring immediate asphalt patch on School Road.",
    riskReason: "High risk of accidents for school children and parents.",
    spamRisk: "Low",
    verificationQuestion: "Is the pothole still visible on the left side of the road?",
    recommendedAction: "Dispatch road maintenance team to fill the pothole.",
    status: "Verified",
    priorityScore: 65,
    priorityReasons: ["High severity", "Located near a school", "12 verifications"],
    verificationCount: 12,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo_uid_communityherocitizen",
    assignedTo: null,
    createdAt: Timestamp.fromDate(addDays(new Date(), -2)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    title: "Series of Potholes on Market Chowk",
    description: "Multiple potholes on the main market road, making it difficult to drive.",
    imageUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80",
    category: "Pothole",
    severity: "Medium",
    confidence: 0.9,
    location: { lat: 28.6239, lng: 77.2190 },
    address: "Market Chowk",
    locationType: "market",
    suggestedDepartment: "Road Maintenance",
    citizenSummary: "Several potholes are damaging vehicles in the market area.",
    authoritySummary: "Medium severity road wear requiring resurfacing.",
    riskReason: "Causes vehicle damage and slow traffic.",
    spamRisk: "Low",
    verificationQuestion: "Are there multiple potholes near the main intersection?",
    recommendedAction: "Schedule road resurfacing for the area.",
    status: "In Progress",
    priorityScore: 50,
    priorityReasons: ["Medium severity", "High-footfall area", "Assigned to department"],
    verificationCount: 7,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo_uid_communityherocitizen",
    assignedTo: "Road Maintenance",
    createdAt: Timestamp.fromDate(addDays(new Date(), -5)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    title: "Small Pothole in Green Park Colony",
    description: "A small pothole has formed near the colony gate.",
    imageUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80",
    category: "Pothole",
    severity: "Low",
    confidence: 0.95,
    location: { lat: 28.6339, lng: 77.2290 },
    address: "Green Park Colony Gate",
    locationType: "residential",
    suggestedDepartment: "Road Maintenance",
    citizenSummary: "A small pothole at the colony entrance.",
    authoritySummary: "Low severity pothole, routine maintenance required.",
    riskReason: "Minor inconvenience.",
    spamRisk: "Low",
    verificationQuestion: "Is the pothole directly in front of the gate?",
    recommendedAction: "Add to routine patching schedule.",
    status: "Open",
    priorityScore: 10,
    priorityReasons: ["Low severity"],
    verificationCount: 0,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo_uid_communityherocitizen",
    assignedTo: null,
    createdAt: Timestamp.fromDate(new Date()),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  // 3 Garbage Overflow
  {
    title: "Overflowing Garbage Bin at Bus Stand",
    description: "The garbage bin near the bus stand has not been cleared for 3 days.",
    imageUrl: "https://images.unsplash.com/photo-1604187351574-c75ca79f5807?auto=format&fit=crop&q=80",
    category: "Garbage Overflow",
    severity: "High",
    confidence: 0.9,
    location: { lat: 28.6439, lng: 77.2390 },
    address: "Bus Stand Lane",
    locationType: "bus stop",
    suggestedDepartment: "Sanitation Department",
    citizenSummary: "Garbage is overflowing onto the street at the bus stand.",
    authoritySummary: "High severity sanitation issue. Missed collection.",
    riskReason: "Health hazard and foul smell affecting commuters.",
    spamRisk: "Low",
    verificationQuestion: "Is the garbage spilling onto the pavement?",
    recommendedAction: "Dispatch sanitation truck immediately.",
    status: "Resolved",
    priorityScore: 70,
    priorityReasons: ["High severity", "Bus stop", "Pending for 3 days"],
    verificationCount: 18,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 12,
    duplicateOf: null,
    createdBy: "demo_uid_communityherocitizen",
    assignedTo: "Sanitation Department",
    createdAt: Timestamp.fromDate(addDays(new Date(), -4)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    title: "Garbage Dumped on Hospital Road",
    description: "People are dumping garbage illegally next to the hospital wall.",
    imageUrl: "https://images.unsplash.com/photo-1595278069441-2cf29f8005a4?auto=format&fit=crop&q=80",
    category: "Garbage Overflow",
    severity: "Critical",
    confidence: 0.95,
    location: { lat: 28.6539, lng: 77.2490 },
    address: "Hospital Road",
    locationType: "hospital",
    suggestedDepartment: "Sanitation Department",
    citizenSummary: "Illegal garbage dumping near the hospital.",
    authoritySummary: "Critical sanitation violation near a healthcare facility.",
    riskReason: "Severe health hazard for patients.",
    spamRisk: "Low",
    verificationQuestion: "Is the garbage right next to the hospital boundary?",
    recommendedAction: "Clear garbage and install warning signs/cameras.",
    status: "Verified",
    priorityScore: 85,
    priorityReasons: ["Critical severity", "Hospital proximity", "25 verifications"],
    verificationCount: 25,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo_uid_communityherocitizen",
    assignedTo: null,
    createdAt: Timestamp.fromDate(addDays(new Date(), -1)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    title: "Missed Garbage Collection in Sector 8",
    description: "Garbage truck didn't visit our lane today.",
    imageUrl: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80",
    category: "Garbage Overflow",
    severity: "Medium",
    confidence: 0.8,
    location: { lat: 28.6639, lng: 77.2590 },
    address: "Sector 8 Main Road",
    locationType: "residential",
    suggestedDepartment: "Sanitation Department",
    citizenSummary: "Garbage collection missed today.",
    authoritySummary: "Routine collection missed in Sector 8.",
    riskReason: "Accumulation of household waste.",
    spamRisk: "Low",
    verificationQuestion: "Are other houses also waiting for collection?",
    recommendedAction: "Ensure truck visits tomorrow.",
    status: "Open",
    priorityScore: 25,
    priorityReasons: ["Medium severity", "3 verifications"],
    verificationCount: 3,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo_uid_communityherocitizen",
    assignedTo: null,
    createdAt: Timestamp.fromDate(new Date()),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  // 2 Water Leakages
  {
    title: "Major Water Pipe Burst on Lake View Street",
    description: "Main water supply pipe burst, flooding the street.",
    imageUrl: "https://images.unsplash.com/photo-1505528637385-eb2e5d95d131?auto=format&fit=crop&q=80",
    category: "Water Leakage",
    severity: "Critical",
    confidence: 0.99,
    location: { lat: 28.6739, lng: 77.2690 },
    address: "Lake View Street",
    locationType: "road",
    suggestedDepartment: "Water Board",
    citizenSummary: "A burst pipe is wasting thousands of liters of water.",
    authoritySummary: "Critical main line burst requiring immediate valve shutoff.",
    riskReason: "Massive water wastage and potential road damage.",
    spamRisk: "Low",
    verificationQuestion: "Is the water still flowing heavily?",
    recommendedAction: "Shut off main valve and repair pipe.",
    status: "In Progress",
    priorityScore: 90,
    priorityReasons: ["Critical severity", "Water wastage", "18 verifications"],
    verificationCount: 18,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo_uid_communityherocitizen",
    assignedTo: "Water Board",
    createdAt: Timestamp.fromDate(addDays(new Date(), -1)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    title: "Leaking Valve near Park",
    description: "Continuous small leak from the water valve outside the park.",
    imageUrl: "https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&q=80",
    category: "Water Leakage",
    severity: "Medium",
    confidence: 0.85,
    location: { lat: 28.6839, lng: 77.2790 },
    address: "Green Park Colony",
    locationType: "park",
    suggestedDepartment: "Water Board",
    citizenSummary: "A small leak from a water valve is wasting water.",
    authoritySummary: "Minor valve leak, requires washer replacement.",
    riskReason: "Continuous water wastage.",
    spamRisk: "Low",
    verificationQuestion: "Is the area around the valve muddy?",
    recommendedAction: "Replace valve washer.",
    status: "Open",
    priorityScore: 20,
    priorityReasons: ["Medium severity", "0 verifications"],
    verificationCount: 0,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo_uid_communityherocitizen",
    assignedTo: null,
    createdAt: Timestamp.fromDate(new Date()),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  // 2 Broken Streetlights
  {
    title: "Streetlights not working at Metro Station Exit",
    description: "The entire row of streetlights outside the metro station is off.",
    imageUrl: "https://images.unsplash.com/photo-1519782550186-b4d45bc839d0?auto=format&fit=crop&q=80",
    category: "Broken Streetlight",
    severity: "High",
    confidence: 0.9,
    location: { lat: 28.6939, lng: 77.2890 },
    address: "Metro Station Exit",
    locationType: "high-footfall area",
    suggestedDepartment: "Electrical Maintenance",
    citizenSummary: "Dark area outside metro station is unsafe for pedestrians at night.",
    authoritySummary: "High severity electrical failure in high traffic area.",
    riskReason: "Major safety and security risk for commuters at night.",
    spamRisk: "Low",
    verificationQuestion: "Are all the lights in that row off?",
    recommendedAction: "Check main power supply and repair.",
    status: "Verified",
    priorityScore: 75,
    priorityReasons: ["High severity", "High-footfall area", "12 verifications"],
    verificationCount: 12,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo_uid_communityherocitizen",
    assignedTo: null,
    createdAt: Timestamp.fromDate(addDays(new Date(), -2)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    title: "Flickering Streetlight in Sector 8",
    description: "One streetlight is flickering continuously.",
    imageUrl: "https://images.unsplash.com/photo-1544026220-410a08e1a179?auto=format&fit=crop&q=80",
    category: "Broken Streetlight",
    severity: "Low",
    confidence: 0.8,
    location: { lat: 28.7039, lng: 77.2990 },
    address: "Sector 8 Main Road",
    locationType: "residential",
    suggestedDepartment: "Electrical Maintenance",
    citizenSummary: "A flickering streetlight is annoying residents.",
    authoritySummary: "Low severity bulb issue.",
    riskReason: "Nuisance to residents.",
    spamRisk: "Low",
    verificationQuestion: "Is it flickering every night?",
    recommendedAction: "Replace bulb/fixture.",
    status: "Confirmed",
    priorityScore: 15,
    priorityReasons: ["Low severity", "Resolved by department", "Confirmed by citizens"],
    verificationCount: 3,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 2,
    duplicateOf: null,
    createdBy: "demo_uid_communityherocitizen",
    assignedTo: "Electrical Maintenance",
    createdAt: Timestamp.fromDate(addDays(new Date(), -10)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  // 1 Sewage Issue
  {
    title: "Overflowing Sewer in Market Area",
    description: "Sewage is overflowing onto the street in the main market.",
    imageUrl: "https://images.unsplash.com/photo-1627889311659-195fa9541a0b?auto=format&fit=crop&q=80",
    category: "Sewage Issue",
    severity: "Critical",
    confidence: 0.95,
    location: { lat: 28.7139, lng: 77.3090 },
    address: "Market Chowk",
    locationType: "market",
    suggestedDepartment: "Drainage Department",
    citizenSummary: "Foul-smelling sewage is flooding the market street.",
    authoritySummary: "Critical drainage blockage causing severe hygiene issues.",
    riskReason: "Extreme health hazard and business disruption.",
    spamRisk: "Low",
    verificationQuestion: "Is the water foul-smelling and dirty?",
    recommendedAction: "Send vacuum truck to clear blockage immediately.",
    status: "In Progress",
    priorityScore: 95,
    priorityReasons: ["Critical severity", "Market area", "25 verifications"],
    verificationCount: 25,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo_uid_communityherocitizen",
    assignedTo: "Drainage Department",
    createdAt: Timestamp.fromDate(new Date()),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  // 1 Damaged Infrastructure
  {
    title: "Broken Bench at Bus Stop",
    description: "The seating bench at the bus stop is broken and unusable.",
    imageUrl: "https://images.unsplash.com/photo-1601002360215-62540b615b6d?auto=format&fit=crop&q=80",
    category: "Damaged Infrastructure",
    severity: "Medium",
    confidence: 0.9,
    location: { lat: 28.7239, lng: 77.3190 },
    address: "Bus Stand Lane",
    locationType: "bus stop",
    suggestedDepartment: "Public Works",
    citizenSummary: "Broken bench means elderly people have nowhere to sit.",
    authoritySummary: "Medium severity infrastructure damage.",
    riskReason: "Inconvenience for commuters.",
    spamRisk: "Low",
    verificationQuestion: "Is the bench completely broken or just cracked?",
    recommendedAction: "Replace or repair the bench.",
    status: "Verified",
    priorityScore: 40,
    priorityReasons: ["Medium severity", "Bus stop", "7 verifications"],
    verificationCount: 7,
    disputeCount: 0,
    duplicateCount: 0,
    confirmedResolvedCount: 0,
    duplicateOf: null,
    createdBy: "demo_uid_communityherocitizen",
    assignedTo: null,
    createdAt: Timestamp.fromDate(addDays(new Date(), -1)),
    updatedAt: Timestamp.fromDate(new Date()),
  }
];

async function seed() {
  const batch = db.batch();
  
  // Also clean up old issues to prevent duplicates when running multiple times
  const oldIssues = await db.collection("issues").get();
  for (const doc of oldIssues.docs) {
    await doc.ref.delete();
  }

  for (const issue of issues) {
    const docRef = db.collection("issues").doc();
    batch.set(docRef, issue);
  }
  await batch.commit();
  console.log("Seeded 12 demo issues");
}

seed().catch(console.error);
